{
  "openapi": "3.0.1",
  "info": {
    "title": "Easy Motel - Sistema de Buscas",
    "description": "O EASY MOTEL é um sistema usado para consulta de disponibilidade de quartos nos Motéis e reservas com base numa cadeia de estabelecimentos cadastrados no sistema.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "description": "Localhost",
      "url": "http://localhost:3000"
    }
  ],
  "paths": {

    "/session": {
      "_comment": "Rotas da SESSION de autenticação - Linha 16",
      "post": {
        "tags": ["Authentication"],
        "summary": "Realizar login na API",
        "description": "Esta rota é responsável por gerar um token JWT para visualização de rotas protegidas",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {"$ref": "#/components/schemas/session-request"},
              "examples": {
                "session-sucess": {
                  "value": {
                    "email": "michely@gmail.com",
                    "senha": "000000"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login realizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/session-response"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos / Usuário não encontrado",
            "content": {
              "application/json": {
                "value": {
                  "error": { "type": "string"}
                }
              }
            }
          }
        }
      }
    },



    "/users": {
      "_comment": "Rotas de USUÁRIOS - Linha 66",
      "get": {
        "tags": ["Usuários"],
        "security": [{ "bearerAuth": []}],
        "summary": "Lista todos os usuários",
        "description": "Esta rota é responsável por listar todos os usuários cadastrados no sistema.",
        "responses": {
          "200": {
            "description": "Listar os usuários cadastrados.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": { "$ref": "#/components/schemas/user-response" }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Usuários"],
        "summary": "Cadastra um novo usuário",
        "description": "Esta rota é responsável por cadastrar um novo usuário",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref" : "#/components/schemas/user-request"},
              "examples": {
                "user-sucess": {
                  "value": {
                    "nome": "Bob Esponja",
                    "email": "bobesponja@email.com",
                    "cpf": "123.456.789.00",
                    "dataNascimento": "1970-01-01",
                    "senha": "123456" 
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Usuário criado com sucesso",
            "content": {
              "application/json":{
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/user-response"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      }
    },

    "/users/{id}": {
      "put": {
        "tags": ["Usuários"],
        "security": [{ "bearerAuth": []}],
        "summary": "Atualiza um usuário existente",
        "description": "Esta rota é responsável por atualizar um usuário cadastrado no sistema.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do usuario atualizado",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/user-request" },
              "examples": {
                "user-sucess": {
                  "value": {
                    "nome": "Bob Esponja Atualizado",
                    "email": "bobesponja@email.com",
                    "cpf": "123.456.789.00",
                    "dataNascimento": "1970-01-01",
                    "senha": "12345678" 
                  }
                }
              }
            }
          }         
        },
        "responses": {
          "200": {
            "description": "Usuário atualizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/user-response"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      },
      "delete": {
        "tags": ["Usuários"],
        "security": [{"bearerAuth": []}],
        "summary": "Deleta um usuário.",
        "description":"Esta rota é responsável por deletar um usuário cadastrado.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do usuário que será deletado",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário deletado com sucesso!"
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      }
    },
    


    
    "/moteis": {
      "_comment": "Rotas de MOTEIS - Linha 213",
      "get": {
        "tags": ["Moteis"],
        "summary": "Lista todos os moteis",
        "description": "Esta rota é responsável por listar todos os moteis cadastrados no sistema.",
        "responses": {
          "200": {
            "description": "Listar os moteis cadastrados.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": { "$ref": "#/components/schemas/moteis-response" }
                }
              }
            }
          }
        }
      },

  
      "post": {
        "tags": ["Moteis"],
        "security": [{ "bearerAuth": []}],
        "summary": "Cadastra um novo motel",
        "description": "Esta rota é responsável por cadastrar um novo motel.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref" : "#/components/schemas/moteis-request"},
              "examples": {
                "user-sucess": {
                  "value": {
                    "nome":"Sonhos Motel",
                     "cnpj": "01.001.001/0001-01",
                    "endereco": {
                      "rua":"Rua dos Sonhos",
                        "numero": "123",
                        "bairro": "Bairro Novo",
                        "cidade": "Fortaleza",
                        "cep": "01.001-001"	
                    }
                  }  
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Motel criado com sucesso",
            "content": {
              "application/json":{
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/moteis-response"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      }
    },

    "/moteis/bairro": {
      "get": {
        "tags": ["Moteis"],
        "summary": "Busca moteis por bairro.",
        "description": "Esta rota é responsável por buscar moteis por bairro.",
        "parameters": [
          {
            "in": "query",
            "name": "nome",
            "description": "Nome do bairro",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Motel encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "$ref": "#/components/schemas/moteis-response"
                }
              }
            }
          },
          "400": {
            "description": "Não encontramos moteis nesse bairro."
          }
        }
      }
    },

    "/moteis/{id}": {
      "put": {
        "tags": ["Moteis"],
        "security": [{ "bearerAuth": []}],
        "summary": "Atualiza um motel existente",
        "description": "Esta rota é responsável por atualizar um motel cadastrado no sistema.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do motel atualizado",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/moteis-request" },
              "examples": {
                "user-sucess": {
                  "value": {
                    "nome":"ama",
                    "cnpj": "22.842.844/0001-37",
                    "endereco": {
                      "rua":"rua de acordar",
                      "numero": "12",
                      "bairro": "aldeota",
                      "cidade": "fortaleza",
                      "cep": "60.841-670"	
                    }
                  }
                }
              }
            }
          }      
        },
        "responses": {
          "200": {
            "description": "Motel atualizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/moteis-request"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      },




      "delete": {
        "tags": ["Moteis"],
        "security": [{"bearerAuth": []}],
        "summary": "Deleta um motel.",
        "description":"Esta rota é responsável por deletar um motel cadastrado.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do motel que será deletado",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Motel deletado com sucesso!"
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      }      
    },


   

    "/motel/quarto": {
      "post": {
        "tags": ["Quartos"],
        "security": [{ "bearerAuth": []}],
        "summary": "Cadastra um novo quarto num motel.",
        "description": "Esta rota é responsável por cadastrar um novo quarto num motel.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref" : "#/components/schemas/quarto-request"},
              "examples": {
                "user-sucess": {
                  "value": {
                    "nome": "Nome do quarto",
                    "valor_quarto": "450.00",
                    "acessorios_quarto": "s",
                    "status": "disponivel",
                    "id_motel": "1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Quarto criado com sucesso",
            "content": {
              "application/json":{
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/quarto-response"
                }
              }
            }
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      }
    },   
    
    
    "/motel/{id}/quartos": {
      "get": {
        "tags": ["Quartos"],
        "security": [{ "bearerAuth": []}],
        "summary": "Lista todos os quartos de um motel específico",
        "description": "Esta rota é responsável por listar todos os quartos de um motel específico.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do motel que você quer ver os quartos.",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Listar os quartos de um motel.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": { "$ref": "#/components/schemas/quarto-request" }
                }
              }
            }
          }
        }
      }
    },

    "/motel/quarto/{id}": {
      "get": {
        "tags": ["Quartos"],
        "security": [{ "bearerAuth": []}],
        "summary": "Buscar por um quarto qualquer pelo ID",
        "description": "Esta rota é responsável por buscar um quarto qualquer em todos os moteis.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do quarto que você quer buscar.",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Buscar por um quarto pelo ID.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": { "$ref": "#/components/schemas/quarto-response" }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Quartos"],
        "security": [{"bearerAuth": []}],
        "summary": "Deleta um quarto.",
        "description":"Esta rota é responsável por deletar um quarto.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do quarto que será deletado",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Quarto deletado com sucesso!"
          },
          "400": {
            "description": "Dados inválidos!"
          },
          "401": {
            "description": "Token inválido ou não informado."
          }
        }
      }      
    }
  },

  



  "components": {
    "schemas": {
      "session-request": {
        "type": "object",
        "properties": {
          "email": { "type": "string" },
          "senha": { "type": "string"}
        }
      },
      "session-response": {
        "type": "object",
        "properties": {
          "usuario": {"type": "object"},
          "token": {"type": "string"}
        }
      },


      "user-request": {
        "type": "object",
        "properties": {
          "nome": { "type": "string"},
          "email":  { "type": "string"},
          "cpf":  { "type": "string"},
          "dataNascimento":  { "type": "string"},
          "senha": { "type": "string"} 
        }
      },
      "user-response": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
		      "nome": { "type": "string" },
		      "email": { "type": "string" }
        }
      },


      "moteis-response": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "nome": { "type": "string" },
          "cnpj": { "type": "string" }
        }
      },

      "moteis-request": {
        "nome": { "type": "string" },
          "cnpj": { "type": "string" },
        "endereco": [{
          "rua": { "type": "string" },
          "numero": { "type": "string" },
          "bairro": { "type": "string" },
          "cidade": { "type": "string" },
          "cep": { "type": "string" }	
        }]
      },



      "quarto-request": {
        "nome": { "type": "string" },
        "valor_quarto": { "type": "number" },
        "acessorios_quarto":  { "type": "string" },
        "status":  { "type": "string" },
        "id_motel": { "type": "string" }
      },
      "quarto-response": {
        "id": { "type": "string" },
        "nome": { "type": "string" },
        "valor_quarto": { "type": "string" },
        "acessorios_quarto": { "type": "string" },
        "status_quarto": { "type": "string" },
        "id_motel": { "type": "string" }
      }
      
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}